'use strict';

/**
 * This module is generated by `gulp refreshAssets`.
 */
export const SpriteSheet =
    /* <generated> */
{ font: [ { x: 0, y: 0, w: 356, h: 6 } ],
  gore:
   [ { x: 0, y: 6, w: 5, h: 5 },
     { x: 5, y: 6, w: 5, h: 5 },
     { x: 10, y: 6, w: 5, h: 5 },
     { x: 15, y: 6, w: 5, h: 5 } ],
  hud_crosshair: [ { x: 0, y: 11, w: 9, h: 9 }, { x: 9, y: 11, w: 9, h: 9 } ],
  hud_healthbar:
   [ { x: 0, y: 20, w: 109, h: 9 },
     { x: 109, y: 20, w: 109, h: 9 },
     { x: 218, y: 20, w: 109, h: 9 } ],
  hud_shells: [ { x: 0, y: 29, w: 6, h: 7 }, { x: 6, y: 29, w: 6, h: 7 } ],
  icon_keys:
   [ { x: 0, y: 36, w: 5, h: 7 },
     { x: 5, y: 36, w: 5, h: 7 },
     { x: 10, y: 36, w: 5, h: 7 },
     { x: 15, y: 36, w: 5, h: 7 } ],
  icon_mouse: [ { x: 0, y: 43, w: 7, h: 9 }, { x: 7, y: 43, w: 7, h: 9 } ],
  page: [ { x: 0, y: 52, w: 12, h: 14 }, { x: 12, y: 52, w: 12, h: 14 } ],
  player:
   [ { x: 0, y: 66, w: 21, h: 32 },
     { x: 21, y: 66, w: 21, h: 32 },
     { x: 42, y: 66, w: 21, h: 32 } ],
  sawblade: [ { x: 0, y: 98, w: 17, h: 17 }, { x: 17, y: 98, w: 17, h: 17 } ],
  shotgun_blast:
   [ { x: 0, y: 115, w: 45, h: 45 },
     { x: 45, y: 115, w: 45, h: 45 },
     { x: 90, y: 115, w: 45, h: 45 },
     { x: 135, y: 115, w: 45, h: 45 } ],
  stabguts:
   [ { x: 0, y: 160, w: 14, h: 22 },
     { x: 14, y: 160, w: 14, h: 22 },
     { x: 28, y: 160, w: 14, h: 22 },
     { x: 42, y: 160, w: 14, h: 22 } ],
  tiles:
   [ { x: 0, y: 182, w: 32, h: 32 },
     { x: 32, y: 182, w: 32, h: 32 },
     { x: 64, y: 182, w: 32, h: 32 } ],
  walls: [ { x: 0, y: 214, w: 4, h: 4 }, { x: 4, y: 214, w: 4, h: 4 } ] }
/* </generated> */
