'use strict';

/**
 * This module is generated by `gulp refreshAssets`.
 */
export const SpriteSheet =
/* <generated> */
{ font: [ { x: 0, y: 0, w: 356, h: 6 } ],
  glyphs:
   [ { x: 0, y: 6, w: 9, h: 9 },
     { x: 9, y: 6, w: 9, h: 9 },
     { x: 18, y: 6, w: 9, h: 9 },
     { x: 27, y: 6, w: 9, h: 9 } ],
  hud_crosshair: [ { x: 0, y: 15, w: 9, h: 9 }, { x: 9, y: 15, w: 9, h: 9 } ],
  hud_healthbar:
   [ { x: 0, y: 24, w: 109, h: 9 },
     { x: 109, y: 24, w: 109, h: 9 },
     { x: 218, y: 24, w: 109, h: 9 } ],
  hud_shells: [ { x: 0, y: 33, w: 6, h: 7 }, { x: 6, y: 33, w: 6, h: 7 } ],
  icon_keys:
   [ { x: 0, y: 40, w: 5, h: 7 },
     { x: 5, y: 40, w: 5, h: 7 },
     { x: 10, y: 40, w: 5, h: 7 },
     { x: 15, y: 40, w: 5, h: 7 } ],
  icon_mouse: [ { x: 0, y: 47, w: 7, h: 9 }, { x: 7, y: 47, w: 7, h: 9 } ],
  monster2: [ { x: 0, y: 56, w: 32, h: 32 }, { x: 32, y: 56, w: 32, h: 32 } ],
  page:
   [ { x: 0, y: 88, w: 12, h: 14 },
     { x: 12, y: 88, w: 12, h: 14 },
     { x: 24, y: 88, w: 12, h: 14 } ],
  particles: [ { x: 0, y: 102, w: 11, h: 11 } ],
  player:
   [ { x: 0, y: 113, w: 21, h: 32 },
     { x: 21, y: 113, w: 21, h: 32 },
     { x: 42, y: 113, w: 21, h: 32 },
     { x: 63, y: 113, w: 21, h: 32 },
     { x: 84, y: 113, w: 21, h: 32 } ],
  sawblade: [ { x: 0, y: 145, w: 17, h: 17 }, { x: 17, y: 145, w: 17, h: 17 } ],
  shot_particle: [ { x: 0, y: 162, w: 2, h: 2 } ],
  shotgun_blast:
   [ { x: 0, y: 164, w: 24, h: 60 },
     { x: 24, y: 164, w: 24, h: 60 },
     { x: 48, y: 164, w: 24, h: 60 },
     { x: 72, y: 164, w: 24, h: 60 } ],
  sparkle: [ { x: 0, y: 224, w: 11, h: 11 } ],
  spitter:
   [ { x: 0, y: 235, w: 19, h: 19 },
     { x: 19, y: 235, w: 19, h: 19 },
     { x: 38, y: 235, w: 19, h: 19 },
     { x: 57, y: 235, w: 19, h: 19 },
     { x: 76, y: 235, w: 19, h: 19 } ],
  tiles:
   [ { x: 0, y: 254, w: 32, h: 32 },
     { x: 32, y: 254, w: 32, h: 32 },
     { x: 64, y: 254, w: 32, h: 32 } ],
  walls2: [ { x: 0, y: 286, w: 46, h: 46 }, { x: 46, y: 286, w: 46, h: 46 } ] }
/* </generated> */
;
