'use strict';

/**
 * This module is generated by `gulp refreshAssets`.
 */
export const SpriteSheet =
    /* <generated> */
{ dialog:
   [ { x: 0, y: 0, w: 15, h: 15 },
     { x: 15, y: 0, w: 15, h: 15 },
     { x: 30, y: 0, w: 15, h: 15 } ],
  font: [ { x: 0, y: 15, w: 180, h: 12 } ],
  gore:
   [ { x: 0, y: 27, w: 5, h: 5 },
     { x: 5, y: 27, w: 5, h: 5 },
     { x: 10, y: 27, w: 5, h: 5 },
     { x: 15, y: 27, w: 5, h: 5 } ],
  hud_crosshair: [ { x: 0, y: 32, w: 9, h: 9 }, { x: 9, y: 32, w: 9, h: 9 } ],
  hud_healthbar:
   [ { x: 0, y: 41, w: 109, h: 9 },
     { x: 109, y: 41, w: 109, h: 9 },
     { x: 218, y: 41, w: 109, h: 9 } ],
  hud_shells: [ { x: 0, y: 50, w: 6, h: 7 }, { x: 6, y: 50, w: 6, h: 7 } ],
  icon_mouse: [ { x: 0, y: 57, w: 7, h: 9 }, { x: 7, y: 57, w: 7, h: 9 } ],
  page: [ { x: 0, y: 66, w: 12, h: 14 }, { x: 12, y: 66, w: 12, h: 14 } ],
  player:
   [ { x: 0, y: 80, w: 21, h: 32 },
     { x: 21, y: 80, w: 21, h: 32 },
     { x: 42, y: 80, w: 21, h: 32 } ],
  sawblade: [ { x: 0, y: 112, w: 17, h: 17 }, { x: 17, y: 112, w: 17, h: 17 } ],
  shotgun_blast:
   [ { x: 0, y: 129, w: 45, h: 45 },
     { x: 45, y: 129, w: 45, h: 45 },
     { x: 90, y: 129, w: 45, h: 45 },
     { x: 135, y: 129, w: 45, h: 45 } ],
  stabguts:
   [ { x: 0, y: 174, w: 14, h: 22 },
     { x: 14, y: 174, w: 14, h: 22 },
     { x: 28, y: 174, w: 14, h: 22 },
     { x: 42, y: 174, w: 14, h: 22 } ],
  tiles: [ { x: 0, y: 196, w: 32, h: 32 } ],
  walls: [ { x: 0, y: 228, w: 4, h: 4 }, { x: 4, y: 228, w: 4, h: 4 } ] }
/* </generated> */
